name: validator_lint
description: A lint making sure all TextFormFields have a validator.

version: 1.0.1
repository: https://github.com/28Apps-Software-GmbH/validator_lint
topics:
  - lints
environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  analyzer: ^8.1.1
  custom_lint_builder: ^0.8.1
  

dev_dependencies:
  lints: ^6.0.0
