name: validator_lint
description: A lint making sure all TextFormFields have a validator.

version: 1.0.0
repository: https://github.com/28Apps-Software-GmbH/validator_lint
topics:
  - lints
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  analyzer: ^7.6.0
  custom_lint_builder: ^0.8.0
  

dev_dependencies:
  lints: ^5.0.0
